name: Branch Deleted
on: delete

env:
  TAG_NAME: ${{ github.event.ref }}

jobs:
  delete:
    strategy:
      fail-fast: false
      matrix:
        component:
          - name: qubership-mistral
            file: Dockerfile
            context: .
          - name: qubership-mistral-tests
            file: tests/robot/Dockerfile
            context: tests/robot
    if: github.event.ref_type == 'branch'
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${GITHUB_ACTOR}
          password: ${{secrets.GITHUB_TOKEN}}
      - name: Prepare Tag
        run: echo "TAG_NAME=$(echo ${TAG_NAME} | sed 's@refs/heads/@@;s@/@_@g')" >> $GITHUB_ENV
      - name: Get package IDs for delete
        id: get-ids-for-delete
        uses: Netcracker/get-package-ids@v0.0.1
        with:
          component-name: ${{ matrix.component.name }}
          component-tag: ${{ env.TAG_NAME }}
          access-token: ${{secrets.GITHUB_TOKEN}}
      - uses: actions/delete-package-versions@v5
        with:
          package-name: ${{ matrix.component.name }}
          package-type: 'container'
          package-version-ids: ${{ steps.get-ids-for-delete.outputs.ids-for-delete }}
        if: ${{ steps.get-ids-for-delete.outputs.ids-for-delete != '' }}